name: maven-build
on: [push]
jobs:
  build:
    runs-on: maven: 3.8.4-openjdk-17
    steps:
      - uses: actions/checkout@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}        
      - run: mvn clean
